input {
  http {
    host => "0.0.0.0"
    port => 5044
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "[@metadata][index]" => "guardiannet-events"
    }
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }

  if [verdict] == "DEEPFAKE" {
    mutate { add_tag => ["alert", "high-severity"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "guardiannet-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
